FROM phusion/ubuntu-lucid-32:latest
MAINTAINER Phusion <info@phusion.nl>

ADD . /bd_build

RUN /bd_build/prepare.sh && \
	/bd_build/system_services.sh && \
	/bd_build/utilities.sh && \
	/bd_build/cleanup.sh

CMD ["/sbin/my_init"]

COPY Dockerfile /Dockerfiles/phusion-baseimage32.latest